version: 0.2
# build image : aws/codebuild/java:openjdk-8-1.6.0
env:
    variables:
      DEV_ACCOUNT_ID: "119334752141"
      PROD_ACCOUNT_ID: "578611160639"
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y docker.io
      - apt-get install -y nodejs
      - apt-get install -y npm
      - echo Build version check...
      - aws --version
      - python --version
      - nodejs -v && node -v
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION --registry-ids ${DEV_ACCOUNT_ID})
  build:
    commands:
      - echo Build started on `date`
      - echo Packaging the jar file...
      - mvn clean package -DskipTests
      - pwd
      - ls -al
      - ls -al ./target/
      #- mvn install dockerfile:build
  post_build:
    commands:
      - echo Building the Docker image... `date`
      - docker build -t hsy-crossaccount-test .
      - docker tag hsy-crossaccount-test ${DEV_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/hsy-crossaccount-test:latest
      - docker push ${DEV_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}:latest
      # Docker tag DEV -> PROD and then upload
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION --registry-ids ${PROD_ACCOUNT_ID})
      - docker tag ${DEV_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/hsy-crossaccount-test:latest ${PROD_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/megazone-repo:latest
      - docker push ${PROD_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/hsy-crossaccount-test:latest
      - docker images
      #- printf '[{"name":"prod-atp-ecr-front","imageUri":"394374453764.dkr.ecr.ap-northeast-2.amazonaws.com/prod-atp-ecr-front:latest"}]' > imagedefinitions.json
      #- printf '[{"name":"${CONTAINER_NAME}","imageUri":"${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${CONTAINER_NAME}:latest"}]' > imagedefinitions.json
#artifacts:
#  files: imagedefinitions.json
